### ISSUE TITLE
Add installation instruction

### ISSUE THREAD

**Issue by daniel-veecle** [veecle/tricore-probe#10]
We should add some instructions in the readme on how to install this (i.e., cargo install --git https://github.com/veecle/tricore-probe). Thoughts? 

@therealfrauholle?

**Comment by therealfrauholle** [comment]
I think that is a good idea :+1:

**Comment by daniel-veecle** [comment]
@arctic-alpaca do you mind making a small PR to take care of this?

**Comment by daniel-veecle** [comment]
This is done btw; closing.
