### ISSUE TITLE
tricore-probe build failed

### ISSUE THREAD

**Issue by aizitf** [veecle/tricore-probe#30]
I followed the link to download the project, and then installed the tools according to the instructions in GitHub. 
https://github.com/veecle/tricore-probe?tab=readme-ov-file#requirements
The following error occurred when compiling:
![image](https://github.com/veecle/tricore-probe/assets/68260096/06bcbb27-c837-4bf9-83aa-b3ada5640d73)
![image](https://github.com/veecle/tricore-probe/assets/68260096/9bb3a952-295a-43d4-a062-030f87273d2e)
![image](https://github.com/veecle/tricore-probe/assets/68260096/583d88bf-ee1e-462c-93bd-3a44ff9de612)
![image](https://github.com/veecle/tricore-probe/assets/68260096/b7295535-b6f6-484b-b028-059a50d0478e)
![image](https://github.com/veecle/tricore-probe/assets/68260096/a0ece154-b0f1-425b-bba9-67093a33df47)
![image](https://github.com/veecle/tricore-probe/assets/68260096/45b61167-1ed1-4577-ab4c-cafb432ed3a1)

**Comment by arctic-alpaca** [comment]
Hi @aizitf,

bindgen seems to generate different bindings than expected.
I cannot reproduce this on the systems I have available, could you share more information about your setup (architecture, windows version, etc).
Are you using the current `main` branch?

While this is might be more of a work-around than a solution and I don't know if there are any other differences between your setup and our expected setup, you can try the following:
* Remove this line: https://github.com/veecle/tricore-probe/blob/main/rust-mcd/build.rs#L7
* Remove these lines: https://github.com/veecle/tricore-probe/blob/main/rust-mcd/build.rs#L13-L54
* Try to compile again.

**Comment by aizitf** [comment]
Here is my message:
windows version: Windows 11 64bits;
current branch:
![image](https://github.com/veecle/tricore-probe/assets/68260096/61b150e5-d64a-47c4-a6e4-2b582cb6d972)
architecture: What does this mean by architecture? My computer or the hardware board I need to test?

I will modify and test according to your instructions, and I will send out the test results later.

**Comment by aizitf** [comment]
@arctic-alpaca Thank you. Now it build ok.
![image](https://github.com/veecle/tricore-probe/assets/68260096/9e5ea7dd-0fd0-47a5-b0fb-9bc6912191f4)
and the tricore-pribe.exe generated.
![image](https://github.com/veecle/tricore-probe/assets/68260096/9be36b5c-9a9b-41e9-9a5f-dcfcdfaba526)
In addition, I would like to ask:
The removed code seems to be used to determine the system environment. Do I need to configure the 'CARGO_CFG_TARGET_OS' variable in the if branch?

**Comment by arctic-alpaca** [comment]
> windows version: Windows 11 64bits;

As far as I'm aware, we have not tested the setup on Windows 11, we might need to investigate this.

> What does this mean by architecture? 

I meant the architecture of the processor, x86(_64) or ARM. But I realized this was visible in your first screenshot.

> The removed code seems to be used to determine the system environment. Do I need to configure the 'CARGO_CFG_TARGET_OS' variable in the if branch?

You do not need to configure anything, this is done by the Cargo build system. The removed code should build the bindings on Windows machines or use pre-built bindings on Linux. For some reason the bindings generated on your system differ from what is generated on our systems. With the code removed, it now uses the pre-built bindings.


> Now it build ok.

Very happy to hear! Let us know if you encounter any other issues.

**Comment by aizitf** [comment]
@arctic-alpaca  ok. Thank you for your help. I have no more questions about this issue.
