### ISSUE TITLE
No working because of the new version of AurixFlasher3.0.0 on Linux

### ISSUE THREAD

**Issue by mrmonopoly-cyber** [veecle/tricore-probe#33]
Hi. I recently started using Aurix and i use Linux. So i have to use the docker env to use the flashing utilities.
I see that in the guide you already have a docker build for this situation but it is based on an old version of the AurixFlasher that i'm not able to find. Right now with the new version it doesn't work (The 3.0.0 is an exe file instead of .msi and so almost a completely different program). I'm working on a fork to fix the problem and i manage to successfully flash my programs by fixing the problem updating to the newer flasher. 
I still have some errors that i'm not really able to understand. If you can help me i would really appreciate that.

In particulary at the end of the flashing there is a error on some regarding the board. (i think)
The program flashed is the example blinky program of the https://github.com/bluewind-embedded-systems/bw-r-drivers-tc37x-examples.git.

The only difference i made was to include this lines in the .cargo/config.toml to automate the build and flash:
```bash
[build]
target="tc162-htc-none"

[target.tc162-htc-none]
runner="tricore-probe"
```
To conclude the command use to build and flash was: 
```bash
Cargo run 
```
And below there is the error

```bash
Device halted, backtrace as follows
0xAFFFC000 -> .Lanon.91f433295d995e56ce08824ca9ec4a3d.19 
??????????? @ ??:0
     0x0 -> defmt::impls::core_::num::<impl defmt::traits::Format for core::num::error::TryFromIntError>::format 
??????????? @ /home/mr_monopoly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/defmt-0.3.6/src/export/integers.rs:6 
```

Thanks in advice for your help. Here also the link to the fork: https://github.com/mrmonopoly-cyber/tricore-probe

**Comment by arctic-alpaca** [comment]
Hi,
Thanks for the report!

I'm looking into updating to AurixFlasher 3.0.0.

As for the blinky error, this looks like a similar issue as mentioned here: https://github.com/bluewind-embedded-systems/bw-r-drivers-tc37x-examples/issues/2

**Comment by mrmonopoly-cyber** [comment]
You are welcome, happy to help. Besides this problem my fork seems to work with AurixFlasher 3.0.0. If you want to merge i can create a pull request.

thanks for redirecting me to the other issue

**Comment by arctic-alpaca** [comment]
> Besides this problem my fork seems to work with AurixFlasher 3.0.0. If you want to merge i can create a pull request.

Thank you for the offer! I'm looking into ways how to automate this as before to hopefully keep the workflow the same, but your fork was helpful.
