### ISSUE TITLE
Make configurable the exit condition of tricore-probe.

### ISSUE THREAD

**Issue by pellico** [veecle/tricore-probe#36]
We are using tricore-probe to run bare-metal code that use only one core.
tricore-probe exit immediately because it check when any core is halted and therefore we cannot see any log message.
I suggest to make the exit condition configurable.
I propose to add a command line option like that:
_--exit-condition_

Values:
* all_halted
* any_halted (default)
* core0_halted
* ....<all other core>

**Comment by arctic-alpaca** [comment]
Hi,
thanks for the suggestion!
We currently don't plan on adding this feature, but PRs are welcome.
